# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_API_BASE_URL
ARG VITE_UI_BASE_URL
ARG VITE_AUTH_ENABLED
ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID
ARG VITE_API_DEDUP_MS
ARG VITE_API_IDEMP_TTL_MS
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_UI_BASE_URL=$VITE_UI_BASE_URL \
    VITE_AUTH_ENABLED=$VITE_AUTH_ENABLED \
    VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL \
    VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM \
    VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID \
    VITE_API_DEDUP_MS=$VITE_API_DEDUP_MS \
    VITE_API_IDEMP_TTL_MS=$VITE_API_IDEMP_TTL_MS
RUN npm run build

# Runtime stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
# HEALTHCHECK CMD wget --spider -q http://localhost || exit 1
CMD ["nginx", "-g", "daemon off;"]

